[project]
name = "instabot-ai"
version = "0.1.0"
description = "Fully automated AI-powered Instagram bot"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "diffusers>=0.32.2",
    "instagrapi>=2.1.3",
    "numpy>=2.2.2",
    "ollama>=0.4.7",
    "torch>=2.6.0",
]
